version: "3.9"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - CURR_ENV=fastapi
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.tasks.worker.celery worker --loglevel=info -Q celery
    env_file:
      - ./.env.prod
    depends_on:
      - rabbit
      - redis
  postgres:
    image: postgres:16.2
    env_file:
      - ./.env.db.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  rabbit:
    image: rabbitmq:3.11.9-management
    hostname: rabbit
    env_file:
      - ./.env.mq.prod
    ports:
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/bitnami/redis/data
  flower:
    image: mher/flower
    env_file:
      - ./.env.mq.prod
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
      - redis

volumes:
  postgres_data: